// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnrVs2vG1YUR8OECOTbLy0PknVL6Pk5vQ',
    appId: '1:60543119460:web:6584908e59356462b92f71',
    messagingSenderId: '60543119460',
    projectId: 'miraki-app',
    authDomain: 'miraki-app.firebaseapp.com',
    storageBucket: 'miraki-app.appspot.com',
    measurementId: 'G-2479ZG7RXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrewk_RnD8CNcahhNVWSAJHoZBol4P12c',
    appId: '1:60543119460:android:54d114062e5f4bafb92f71',
    messagingSenderId: '60543119460',
    projectId: 'miraki-app',
    storageBucket: 'miraki-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvlbZUeGwRgcqy7ZdiFPndnvQYDAMvIs',
    appId: '1:60543119460:ios:ba035839343a822db92f71',
    messagingSenderId: '60543119460',
    projectId: 'miraki-app',
    storageBucket: 'miraki-app.appspot.com',
    iosClientId: '60543119460-c6vlr1ilcoe5d898l0cluhb658gtgiov.apps.googleusercontent.com',
    iosBundleId: 'com.example.mirakiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFvlbZUeGwRgcqy7ZdiFPndnvQYDAMvIs',
    appId: '1:60543119460:ios:ba035839343a822db92f71',
    messagingSenderId: '60543119460',
    projectId: 'miraki-app',
    storageBucket: 'miraki-app.appspot.com',
    iosClientId: '60543119460-c6vlr1ilcoe5d898l0cluhb658gtgiov.apps.googleusercontent.com',
    iosBundleId: 'com.example.mirakiApp',
  );
}
